session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: Demmenty@gmail.com
  password: farselty
database:
  host: localhost
  port: 5432
  user: postgres
  password: queef
  database: vkbot_base
bot:
  token: vk1.a.Rlo3gn9MxYKdYdrKLYeLkrIkaI9fpKwG6_X1xTp3XtNuvrdA7s1kU3l3AG_I2jmtTiClVdz418q3JivrijdKSfkc-5M2C65Bs4IZHJLWQ6-k90Xoj1yeKD49Su1Wa7PpIfc7RQpoY1cFvFsGNVpPCVw0QJwUVctVr13-rXG69MoKBNs3-t6FV44zeG_B6cradrAsDMqi3cwy862DEFq3cA
  group_id: 218753438
server:
  host: localhost
