"""create relationships

Revision ID: 54f8ec4558a1
Revises: 7c8794918ef9
Create Date: 2023-03-01 12:09:22.341176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f8ec4558a1'
down_revision = '7c8794918ef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_user_id_fkey', 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'vk_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key('player_user_id_fkey', 'player', 'vk_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
