"""fields added

Revision ID: 683e62e1c8e7
Revises: 79b24f42d574
Create Date: 2023-03-06 18:32:49.484010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683e62e1c8e7'
down_revision = '79b24f42d574'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('casino_cash', sa.Integer(), nullable=False))
    op.add_column('chat', sa.Column('games_played', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('games_played', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('games_won', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('games_lost', sa.Integer(), nullable=False))
    op.add_column('vk_user', sa.Column('sex', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vk_user', 'sex')
    op.drop_column('player', 'games_lost')
    op.drop_column('player', 'games_won')
    op.drop_column('player', 'games_played')
    op.drop_column('chat', 'games_played')
    op.drop_column('chat', 'casino_cash')
    # ### end Alembic commands ###
