"""update

Revision ID: 7e738b5b6198
Revises: daad4a9a1f6f
Create Date: 2023-03-05 18:20:11.713817

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '7e738b5b6198'
down_revision = 'daad4a9a1f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
