"""rename fields

Revision ID: 93e341ab69be
Revises: 683e62e1c8e7
Create Date: 2023-03-06 19:23:40.350710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e341ab69be'
down_revision = '683e62e1c8e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('vk_id', sa.Integer(), nullable=False))
    op.drop_constraint('chat_vk_peer_id_key', 'chat', type_='unique')
    op.create_unique_constraint(None, 'chat', ['vk_id'])
    op.drop_column('chat', 'vk_peer_id')
    op.add_column('vk_user', sa.Column('vk_id', sa.Integer(), nullable=False))
    op.drop_column('vk_user', 'vk_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_user', sa.Column('vk_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('vk_user', 'vk_id')
    op.add_column('chat', sa.Column('vk_peer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat', type_='unique')
    op.create_unique_constraint('chat_vk_peer_id_key', 'chat', ['vk_peer_id'])
    op.drop_column('chat', 'vk_id')
    # ### end Alembic commands ###
