"""create relationships

Revision ID: b5b8d08045d1
Revises: 54f8ec4558a1
Create Date: 2023-03-01 12:11:35.763621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b8d08045d1'
down_revision = '54f8ec4558a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
