"""player.bet + player.is_active added

Revision ID: c9ba4558be96
Revises: e2b0c43ed964
Create Date: 2023-03-02 21:09:27.398031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ba4558be96'
down_revision = 'e2b0c43ed964'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('bet', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_active')
    op.drop_column('player', 'bet')
    # ### end Alembic commands ###
