"""update

Revision ID: daad4a9a1f6f
Revises: 79b24f42d574
Create Date: 2023-03-05 18:19:58.096657

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'daad4a9a1f6f'
down_revision = '79b24f42d574'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
