"""player.cash added

Revision ID: e2b0c43ed964
Revises: 10fdb41a71b1
Create Date: 2023-03-02 21:00:34.244865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b0c43ed964'
down_revision = '10fdb41a71b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('cash', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'cash')
    # ### end Alembic commands ###
